# Generated by Django 5.0.3 on 2024-03-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider/image', verbose_name='slider rasmini kiriting')),
                ('text1', models.CharField(max_length=200)),
            ],
        ),
    ]
