# Generated by Django 5.0.3 on 2024-03-30 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_slider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='descrtiption',
        ),
        migrations.AddField(
            model_name='category',
            name='descrtiption',
            field=models.TextField(default=1, max_length=1000, verbose_name="Kategoriya haqida ma'lumot"),
            preserve_default=False,
        ),
    ]
