# Generated by Django 5.0.3 on 2024-03-30 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_remove_books_descrtiption_category_descrtiption'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='descrtiption',
            field=models.TextField(default=1, max_length=1000, verbose_name="Kitob haqida ma'lumot"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.author', verbose_name='Muallifni tanlang'),
        ),
    ]
