# Generated by Django 5.0.3 on 2024-03-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_alter_books_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ourteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fi', models.CharField(max_length=80)),
                ('photo', models.ImageField(upload_to='team/image', verbose_name='slider rasmini kiriting')),
                ('occupation', models.CharField(max_length=70)),
                ('twitter', models.CharField(max_length=110)),
                ('facebook', models.CharField(max_length=170)),
                ('linkedin', models.CharField(max_length=170)),
                ('instagram', models.CharField(max_length=170)),
            ],
        ),
    ]
