# Generated by Django 5.0.3 on 2024-03-31 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_ourteam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='describtion',
            new_name='description',
        ),
    ]
