# Generated by Django 5.0.3 on 2024-04-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_alter_books_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reklama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='reklama/image', verbose_name='Reklama')),
                ('data_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
