# Generated by Django 5.0.2 on 2024-04-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0017_books_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='country',
            field=models.CharField(blank=True, choices=[("O'Z", "O'zbekcha"), ('RU', 'Ruscha'), ('TU', 'Turkcha'), ('ENG', 'Inglizcha')], max_length=100, null=True),
        ),
    ]
